In [1]:
# replace all odd numbers in arr with -1

In [2]:
import numpy as np

In [3]:
import sys

In [4]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
print(f''' array:{arr}''')

 array:[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr[arr%2 !=0]=-1

In [7]:
print(f''' modified array:{arr}''')

 modified array:[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
#convert a 1D array to a 2D array with 2 rows

In [9]:
arr=np.arange(10)

In [10]:
print(f''' array:{arr}''')

 array:[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr=arr.reshape(2,-1)

In [12]:
print(f'''reshaped array with 2 rows:{arr}''')

reshaped array with 2 rows:[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
#create the following pattern without hardcoding .Use only numpy functions and the below input array arr=np.array([1,2,3]).

In [14]:
arr=np.array([1,2,3])

In [15]:
print(f'''array:{arr}''')

array:[1 2 3]


In [16]:
a=np.repeat(arr[0],2)

In [17]:
b=np.repeat(arr[1],3)

In [18]:
c=np.repeat(arr[2],3)

In [20]:
d=np.tile(arr,3)

In [21]:
k=np.r_[a,b,c,d]

In [22]:
print(f'''desired output pattern :{k}''')

desired output pattern :[1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [23]:
#get the common items between a and b .a=np.array([1,2,3,2,3,4,3,4,5,6]),b=np.array([7,2,10,2,7,4,9,4,9,8])

In [24]:
a=np.array([1,2,3,2,3,4,3,4,5,6])

In [25]:
print(f''' array a:{a}''')

 array a:[1 2 3 2 3 4 3 4 5 6]


In [26]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [27]:
print(f'''array b:{b}''')

array b:[ 7  2 10  2  7  4  9  4  9  8]


In [28]:
com=np.intersect1d(a,b)

In [29]:
print(f'''common items:{com}''')

common items:[2 4]


In [30]:
match=np.where(a==b)

In [31]:
print(f'''a and b match at index locations:{match}''')

a and b match at index locations:(array([1, 3, 5, 7], dtype=int64),)


In [32]:
#create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [33]:
a=np.random.uniform(5,10,size=15).reshape(5,3)

In [34]:
print(f'''2D array of shape 5x3 to contain random decima numbers between 5 and 10:{a}''')

2D array of shape 5x3 to contain random decima numbers between 5 and 10:[[9.4648826  6.03601211 5.27096762]
 [7.15325551 8.2116954  8.81016523]
 [9.07784869 8.86012244 8.12554454]
 [8.59395644 9.20592939 5.80440402]
 [6.30821173 5.6036294  8.82467035]]


In [35]:
#limit the number of items printed in python numpy array a to a maximum of 6 elements.arr=np.arrange(15).

In [36]:
arr=np.arange(15)

In [37]:
print(f'''array:{arr}''')

array:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [38]:
np.set_printoptions(threshold=6)

In [39]:
print(f'''same array with max 6 elements displayed:{arr}''')

same array with max 6 elements displayed:[ 0  1  2 ... 12 13 14]


In [42]:
#how to pretty print a numpy array by suppressing the scientific notation ?

In [43]:
np.random.seed(100)

In [44]:
rand_arr=np.random.random_sample([3,3])/1e3

In [45]:
print(f'''array:{rand_arr}''')

array:[[5.43404942e-04 2.78369385e-04 4.24517591e-04]
 [8.44776132e-04 4.71885619e-06 1.21569121e-04]
 [6.70749085e-04 8.25852755e-04 1.36706590e-04]]


In [47]:
np.set_printoptions(suppress=True,precision=6)

In [48]:
print(f'''array:{rand_arr}''')

array:[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [49]:
np.set_printoptions(suppress=False,precision=9)

In [50]:
#swap columns 1 and2

In [51]:
arr=np.arange(9).reshape(3,3)

In [52]:
print(f'''array:{arr}''')

array:[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
u=arr[:,[1,0,2]]

In [54]:
print(f'''array with 1st and 2 nd colums swapped:{u}''')

array with 1st and 2 nd colums swapped:[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [55]:
#swap rows 1 and 2

In [56]:
arr=np.arange(9).reshape(3,3)

In [57]:
print(f''' array:{arr}''')

 array:[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
u=arr[[1,0,2],:]

In [59]:
print(f'''array with 1 and 2 rows swapped:{u}''')

array with 1 and 2 rows swapped:[[3 4 5]
 [0 1 2]
 [6 7 8]]
