In [1]:
# multiply the two matrices
#input:X=[[1,4,3],[3,5,6],[6,7,9]]    Y=[[1,2,5,12],[6,7,3,0],[4,7,9,11]]

In [2]:
import numpy as np 

In [3]:
x=[[1,4,3],[3,5,6],[6,7,9]]

In [4]:
y=[[1,2,5,12],[6,7,3,0],[4,7,9,11]]

In [5]:
print(f''' x:{x}''')

 x:[[1, 4, 3], [3, 5, 6], [6, 7, 9]]


In [6]:
print(f'''y:{y}''')

y:[[1, 2, 5, 12], [6, 7, 3, 0], [4, 7, 9, 11]]


In [7]:
a=np.array(x)

In [8]:
b=np.array(y)

In [9]:
c=(np.dot(a,b))

In [10]:
print(f''' multiplication of matrices x and y:{c}''')

 multiplication of matrices x and y:[[ 37  51  44  45]
 [ 57  83  84 102]
 [ 84 124 132 171]]


In [11]:
#extract all numbers divisible by 3 from the array .  input:arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])

In [12]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])

In [13]:
print(f''' array:{arr}''')

 array:[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
arr[arr%3==0]

array([ 0,  3,  6,  9, 12])

In [15]:
#how t get the unique common items between two python numpy arrays?
#get the unique common items between a and b.  input:a=([1,2,3,2,3,4,3,4,5,6])  b=([7,2,10,2,7,4,9,4,9,8])

In [16]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [17]:
print(f'''array a:{a}''')

array a:[1 2 3 2 3 4 3 4 5 6]


In [18]:
print(f'''array b:{b}''')

array b:[ 7  2 10  2  7  4  9  4  9  8]


In [19]:
com=np.intersect1d(a,b)

In [20]:
print(f'''unique common items between a and b:{com}''')

unique common items between a and b:[2 4]


In [21]:
#how to remove from one array those items that exist in another?
#from array a remove all items present in array b input:a=np.array([1,2,3,4,,11,22,33,44,55])  b=np.array([5,6,7,8,9,10,11])

In [22]:
a=np.array([1,2,3,4,5,11,22,33,44,55])
b=np.array([5,6,7,8,9,10,11])

In [23]:
print(f'''array a:{a}''')
print(f'''array b:{b}''')

array a:[ 1  2  3  4  5 11 22 33 44 55]
array b:[ 5  6  7  8  9 10 11]


In [24]:
c=np.setdiff1d(a,b)
print(f'''array a, after removing common items found in b:{c}''')

array a, after removing common items found in b:[ 1  2  3  4 22 33 44 55]


In [ ]:
#how to get the positions